---
- name: Converge
  hosts: all
  serial: 1
  tasks:
    - name: Wait for ES to be reachable from this container
      ansible.builtin.uri:
        url: "http://elasticsearch-test:9200/_cluster/health"
        method: GET
        status_code: 200
      register: curator_es_check
      retries: 30
      delay: 5
      until: curator_es_check.status == 200

    - name: Create test index
      ansible.builtin.uri:
        url: "http://elasticsearch-test:9200/test-index"
        method: PUT
        status_code:
          - 200
          - 400  # Already exists

    - name: Include curator role
      ansible.builtin.include_role:
        name: boutetnico.curator
      vars:
        curator_hosts:
          - "http://elasticsearch-test:9200"
        curator_systemd_config:
          curator.service:
            Unit:
              Description: Run of Elasticsearch Curator
              Wants: curator.timer
            Service:
              Type: oneshot
              ExecStart: /usr/local/bin/curator --config /etc/curator/curator.yml /etc/curator/actionfile.yml
            Install:
              WantedBy: multi-user.target
          curator.timer:
            Unit:
              Description: Hourly run of Elasticsearch Curator
              Requires: curator.service
            Timer:
              Unit: curator.service
              OnCalendar: hourly
            Install:
              WantedBy: timers.target
        curator_actions:
          actions:
            1:
              action: delete_indices
              description: Delete test-index
              options:
                ignore_empty_list: true
              filters:
                - filtertype: pattern
                  kind: prefix
                  value: test-

    - name: Run curator manually to verify it works
      ansible.builtin.command:
        cmd: /usr/local/bin/curator --config /etc/curator/curator.yml /etc/curator/actionfile.yml
      changed_when: false

    - name: Verify test index was deleted
      ansible.builtin.uri:
        url: "http://elasticsearch-test:9200/test-index"
        method: GET
        status_code: 404
